/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LineItem: typeof import('./src/components/LineItem.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NFlex: typeof import('naive-ui')['NFlex']
    NSpace: typeof import('naive-ui')['NSpace']
  }
}
